@authToken = eb57402c-4692-4234-b312-7d28cc96a824
@host = http://localhost:9000

### DEMO

### Creates a new user
POST {{host}}/users
Content-Type: application/json

{
    "name": "Jonh",
    "email": "jonh@gmail.com"
}

### Creates a new user
POST {{host}}/users
Content-Type: application/json

{
    "name": "David",
    "email": "david@gmail.com"
}

### Create an Invalid user
POST {{host}}/users
Content-Type: application/json

{
    "name": "Colton",
    "email": "david@gmail.com"
}

### Returns user information
GET {{host}}/users/me
Authorization: {{authToken}}

### Creates a new club
POST {{host}}/clubs
Content-Type: application/json
Authorization: {{authToken}}

{
    "name": "Fly Padel"
}

### Creates a new club
POST {{host}}/clubs
Content-Type: application/json
Authorization: {{authToken}}

{
    "name": "Padel Club"
}

### Create new court
POST {{host}}/courts
Content-Type: application/json
Authorization: {{authToken}}

{
    "name": "Court 1",
    "cid": 1 
}

### Create new court
POST {{host}}/courts
Content-Type: application/json
Authorization: {{authToken}}

{
    "name": "Court 2",
    "cid": 1 
}

### List Courts of a club
GET {{host}}/courts/clubs/1

### Get available hours for court rental
POST {{host}}/courts/1/available
Authorization: {{authToken}}
Content-Type: application/json

{
    "date": "2025-04-26"
}

### Create a invalid date rental
POST {{host}}/rentals
Content-Type: application/json
Authorization: {{authToken}}

{
    "cid": 1,
    "crid": 1,
    "date": "2025-03-22",
    "initialHour": 8,
    "finalHour": 10
}


### Create a new rental
POST {{host}}/rentals
Content-Type: application/json
Authorization: {{authToken}}

{
    "cid": 1,
    "crid": 1,
    "date": "2025-04-27",
    "initialHour": 8,
    "finalHour": 10
}

### Create a new rental
POST {{host}}/rentals
Content-Type: application/json
Authorization: {{authToken}}

{
    "cid": 1,
    "crid": 1,
    "date": "2025-04-27",
    "initialHour": 10,
    "finalHour": 12
}

### Create a new rental
POST {{host}}/rentals
Content-Type: application/json
Authorization: {{authToken}}

{
    "cid": 1,
    "crid": 1,
    "date": "2025-04-27",
    "initialHour": 18,
    "finalHour": 22
}


### Get available hours for court rentals
POST {{host}}/courts/1/available
Authorization: {{authToken}}
Content-Type: application/json

{
    "date": "2025-04-27"
}

### Get a list with the rentals
GET {{host}}/rentals/courts/1

### Get rental details
GET {{host}}/rentals/1

### Get a list with the rentals
GET {{host}}/rentals/courts/1?skip=0&limit=2

### Delete a rental
DELETE {{host}}/rentals/1
Authorization: {{authToken}}

### Show details of deleted rental
GET {{host}}/rentals/1
